In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
dataset=pd.read_excel(r'DATA.xlsx',sheet_name='2020')

In [ ]:
data=pd.read_excel(r'DATA.xlsx')

In [ ]:
dataset.head()

Unnamed: 0         Unnamed: 1 Unnamed: 2                   Unnamed: 3  \
0      S. No  State/UT/District   Homicide  Causing death by negligence   
1          1         Ahmednagar        254                          620   
2          2              Akola        114                          116   
3          3           Amravati        201                          354   
4          4          Aurangbad        139                          386   

  Unnamed: 4        Unnamed: 5                Unnamed: 6          Unnamed: 7  \
0       Hurt  Assault on woman  Kidnapping and abduction  Human trafficking    
1       1826               543                       369                   0   
2       1345               245                        76                   0   
3       2133               461                       190                   0   
4       1869               335                       242                   0   

  Unnamed: 8                          Unnamed: 9  ...    Unnamed: 12  \
0       Rape  Offence against public tranquility  ...  Miscellaneous   
1         92                                 905  ...          30535   
2         28                                 111  ...           4244   
3         97                                 144  ...           3921   
4         80                                 428  ...           4292   

  Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18  \
0      Others       Total  Population  Crime Rate   Sex Ratio    Literacy   
1         221       38689     4543159    0.851588         939      0.7905   
2         213        7524     1813906    0.414795         946      0.8805   
3         164       10113     2888445    0.350119         951      0.8738   
4         411       12268     3701282    0.331453         923      0.7902   

  Unnamed: 19 Unnamed: 20 Unnamed: 21  
0     Density    Latitude   Longitude  
1         266   19.094829   74.747979  
2         320   20.700216   77.008168  
3         237   20.931982   77.752304  
4         366   19.876165   75.343314  

[5 rows x 22 columns]

In [ ]:
for col in data:
    print (type(data[col][1]))

<class 'int'>
<class 'str'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>
<class 'float'>


# Extracting Independent and dependent Variable 

In [ ]:

x= dataset.iloc[:, [2,3,4,5,6,7,8,9,10,11,12,13,14]].values  
y= dataset.iloc[:, [20,21]].values    

In [ ]:
x

array([['Homicide', 'Causing death by negligence', 'Hurt',
        'Assault on woman', 'Kidnapping and abduction',
        'Human trafficking ', 'Rape',
        'Offence against public tranquility',
        'Offences against property',
        'Offences relating to documents and property marks',
        'Miscellaneous', 'Others', 'Total'],
       [254, 620, 1826, 543, 369, 0, 92, 905, 3104, 220, 30535, 221,
        38689],
       [114, 116, 1345, 245, 76, 0, 28, 111, 946, 86, 4244, 213, 7524],
       [201, 354, 2133, 461, 190, 0, 97, 144, 2198, 250, 3921, 164,
        10113],
       [139, 386, 1869, 335, 242, 0, 80, 428, 3821, 265, 4292, 411,
        12268],
       [206, 308, 1233, 248, 91, 0, 50, 508, 1002, 104, 1858, 111, 5719],
       [41, 141, 486, 88, 71, 0, 16, 43, 676, 60, 1051, 54, 2727],
       [122, 293, 2099, 313, 110, 0, 36, 320, 1269, 102, 3024, 104, 7792],
       [105, 234, 1147, 194, 152, 1, 46, 84, 980, 108, 2235, 355, 5641],
       [84, 352, 433, 80, 98, 1, 14, 205, 78

In [ ]:
y

array([['Latitude', 'Longitude'],
       [19.0948287, 74.7479789],
       [20.7002159, 77.0081678],
       [20.9319821, 77.7523039],
       [19.8761653, 75.3433139],
       [18.990088, 75.7531324],
       [21.177658, 79.6570127],
       [20.5292147, 76.1841701],
       [19.9615398, 79.2961468],
       [20.9042201, 74.7748979],
       [20.184871, 79.9947956],
       [21.4549477, 80.1960712],
       [19.7173703, 77.1493722],
       [21.0076578, 75.5626039],
       [19.8346659, 75.8816345],
       [16.7049873, 74.2432527],
       [18.4087934, 76.5603828],
       [19.0759837, 72.8776559],
       [19.1538231, 72.8751786],
       [21.1458004, 79.0881546],
       [19.1382514, 77.3209555],
       [21.7468548, 74.123996],
       [19.9974533, 73.7898023],
       [18.185332, 76.0419642],
       [19.2608384, 76.774776],
       [18.5204303, 73.8567437],
       [18.2376278, 73.4445392],
       [16.990215, 73.3120233],
       [16.8523973, 74.5814773],
       [17.6804639, 74.018261],
       [16.349219

# Splitting the dataset into training and test set  

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 

In [ ]:
x_train

array([[18, 50, 241, 53, 18, 0, 6, 43, 178, 48, 330, 14, 999],
       [336, 814, 3187, 746, 1159, 30, 243, 687, 6209, 1211, 8009, 997,
        23628],
       [5659, 11174, 47014, 9965, 8103, 168, 2148, 10695, 75908, 10824,
        189581, 22778, 394017],
       [114, 110, 855, 163, 66, 0, 24, 142, 449, 39, 3699, 29, 5690],
       [145, 359, 1017, 275, 192, 2, 49, 481, 1557, 183, 2986, 162, 7408],
       [86, 170, 1394, 197, 113, 0, 25, 44, 741, 88, 1980, 24, 4862],
       [105, 234, 1147, 194, 152, 1, 46, 84, 980, 108, 2235, 355, 5641],
       [192, 439, 901, 259, 187, 0, 34, 440, 2045, 248, 4353, 256, 9354],
       [206, 308, 1233, 248, 91, 0, 50, 508, 1002, 104, 1858, 111, 5719],
       [521, 349, 4171, 1553, 1180, 58, 331, 392, 17530, 3425, 19788,
        9146, 58444],
       [133, 209, 1436, 208, 100, 0, 36, 411, 1618, 170, 1164, 770, 6255],
       [122, 293, 2099, 313, 110, 0, 36, 320, 1269, 102, 3024, 104, 7792],
       [39, 106, 250, 53, 43, 0, 11, 109, 361, 113, 388, 18, 1491],

In [ ]:
x_test

array([[79, 232, 466, 158, 217, 4, 62, 95, 1859, 500, 1827, 85, 5584],
       [62, 133, 255, 44, 57, 0, 17, 116, 429, 38, 2930, 3053, 7134],
       [104, 244, 1077, 138, 111, 3, 26, 303, 964, 94, 2000, 82, 5146],
       [65, 135, 303, 55, 32, 0, 17, 21, 302, 41, 427, 27, 1425],
       [246, 461, 2437, 449, 276, 8, 96, 786, 3046, 289, 2906, 3744,
        14744],
       [207, 269, 1344, 250, 228, 2, 39, 340, 1678, 197, 1756, 293, 6603],
       [146, 313, 1020, 263, 150, 15, 54, 388, 1357, 222, 5190, 202,
        9320],
       [50, 131, 311, 57, 40, 0, 18, 23, 400, 30, 996, 134, 2190],
       [114, 116, 1345, 245, 76, 0, 28, 111, 946, 86, 4244, 213, 7524],
       [649, 1102, 3540, 936, 1113, 28, 243, 1227, 7935, 999, 37271, 771,
        55814]], dtype=object)

In [ ]:
y_train

array([[16.3492193, 73.5594128],
       [19.2183307, 72.9780897],
       [nan, nan],
       [20.1119123, 77.1312586],
       [17.6804639, 74.018261],
       [20.745319, 78.6021946],
       [19.9615398, 79.2961468],
       [21.0076578, 75.5626039],
       [18.990088, 75.7531324],
       [19.0759837, 72.8776559],
       [19.8346659, 75.8816345],
       [20.5292147, 76.1841701],
       [16.990215, 73.3120233],
       [19.0948287, 74.7479789],
       [19.7173703, 77.1493722],
       [18.2376278, 73.4445392],
       [19.2608384, 76.774776],
       [21.177658, 79.6570127],
       [18.185332, 76.0419642],
       [19.8761653, 75.3433139],
       [19.1538231, 72.8751786],
       [21.7468548, 74.123996],
       [21.1458004, 79.0881546],
       [20.9042201, 74.7748979],
       [20.3899385, 78.1306846],
       [20.9319821, 77.7523039],
       ['Latitude', 'Longitude']], dtype=object)

In [ ]:
y_test

array([[19.9974533, 73.7898023],
       [19.1382514, 77.3209555],
       [18.4087934, 76.5603828],
       [20.184871, 79.9947956],
       [17.6599188, 75.9063906],
       [16.8523973, 74.5814773],
       [16.7049873, 74.2432527],
       [21.4549477, 80.1960712],
       [20.7002159, 77.0081678],
       [18.5204303, 73.8567437]], dtype=object)

# Fitting K-NN classifier to the training set  

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train) 

ValueError: ignored